stages:
  - prepare
  - build

before_script:
  - git clone https://github.com/flutter/flutter.git -b stable

prepare_macos:
  stage: prepare
  tags:
    - macos
  script:
    - export PATH="$PATH:`pwd`/flutter/bin"
    - flutter doctor

#prepare_windows:
#  stage: prepare
#  tags:
#    - windows
#  script:
#    - flutter doctor
#
#prepare_linux:
#  stage: prepare
#  tags:
#    - linux
#  script:
#    - flutter doctor

build_android:
  stage: build
  tags:
    - macos
  script:
    - flutter clean
    - echo "$KEY_PROPERTIES" > android/key.properties
    - flutter build appbundle --release
  artifacts:
      name: Android Release
      paths:
          - build/app/outputs/bundle/release/app-release.aab

build_ios:
  stage: build
  tags:
    - macos
  script:
    - flutter clean
    - flutter build ios --release --no-codesign
    - cd build/ios/iphoneos
    - mkdir Payload
    - mv Runner.app Payload/Runner.app
    - zip -r build.ipa Payload
  artifacts:
      name: iOS Release
      paths:
          - build/ios/iphoneos/build.ipa