name: Flutter Build

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set PATH
        run: export PATH="$PATH":"$HOME/development/flutter/bin"
      - name: Set up Flutter
        run: flutter upgrade
      - name: Build Linux
        run: flutter build linux --release
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: build/linux/x64/release/bundle/

  #build-macos-ios:
  #  runs-on: macos-ventura
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
#
  #    - name: Set up Flutter
  #      run: flutter upgrade
#
  #    - name: Build macOS and iOS
  #      run: flutter build macos && flutter build ios
#
  #build-android:
  #  runs-on: macos-ventura
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
#
  #    - name: Set up Flutter
  #      run: flutter upgrade
#
  #    - name: Build Android
  #      run: flutter build apk
#
  #build-windows:
  #  runs-on: windows
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
#
  #    - name: Set up Flutter
  #      run: flutter upgrade
#
  #    - name: Build Windows
  #      run: flutter build windows
